FROM node:24-alpine AS builder
WORKDIR /api

COPY ./api/package*.json ./
RUN npm ci

COPY ./api/ ./
RUN npm run build

RUN npm prune --omit=dev

FROM node:24-alpine AS runner
WORKDIR /api

ENV NODE_ENV=production

COPY --from=builder /api/node_modules ./node_modules
COPY --from=builder /api/dist ./dist
COPY --from=builder /api/package.json ./package.json

USER node

EXPOSE 3001
CMD ["node", "dist/server.js"]
